//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ_номенклатура
    {
        public int Код_заказ_номенклатура { get; set; }
        public Nullable<int> Количество_со_склада { get; set; }
        public Nullable<int> Код_номенклатуры { get; set; }
        public Nullable<int> Код_Заказа { get; set; }
        public Nullable<int> Количество_для_изготовления { get; set; }
        public string Статус_заявки { get; set; }
    
        public virtual Заказ Заказ { get; set; }
        public virtual Номенклатура Номенклатура { get; set; }
    }
}
