//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказ()
        {
            this.Заказ_номенклатура = new HashSet<Заказ_номенклатура>();
        }
    
        public int Код_Заказа { get; set; }
        public Nullable<int> Код_клиента { get; set; }
        public Nullable<System.DateTime> Дата_заказа { get; set; }
        public Nullable<int> Итоговая_стоимость { get; set; }
        public Nullable<int> Код_мастера { get; set; }
        public Nullable<int> Количество { get; set; }
        public string Статус_заказа { get; set; }
    
        public virtual Клиент Клиент { get; set; }
        public virtual Мастер Мастер { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказ_номенклатура> Заказ_номенклатура { get; set; }
    }
}
