//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Номенклатура
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Номенклатура()
        {
            this.Заказ_номенклатура = new HashSet<Заказ_номенклатура>();
        }
    
        public int Код_номенклатуры { get; set; }
        public string Наименование { get; set; }
        public Nullable<int> Стоимость { get; set; }
        public Nullable<int> Количество_на_складе { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказ_номенклатура> Заказ_номенклатура { get; set; }
    }
}
